### PR TITLE
convert double_bubble to C++

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

This changes the boundary conditions to use the centralized BCs and also puts the initial
model into the model_parser data structures.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
this crashes: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-15-001/index.html

**Comment by zingale** [comment]
this takes one more step now than the benchmark, but manually comparing the files shows:
```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------
 level =  1
 density                           0.1115628510E-05          0.6756895483E-03
 xmom                              0.2244872260E-02          0.1068547608E-01
 ymom                              0.3711370639E-01          0.9632307591E-01
 zmom                               0.000000000               0.000000000    
 rho_E                              25720.89643              0.1037040417E-01
 rho_e                              25723.08108              0.1037128707E-01
 Temp                              0.5311598319E-02          0.4414354713E-03
 rho_A                             0.3732816321E-04          0.2260810790E-01
 rho_B                             0.3628613516E-04          0.3538981122E-01
 rho_C                             0.3651454702E-04          0.3556178020E-01
 phiGrav                            0.000000000               0.000000000    
 grav_x                             0.000000000               0.000000000    
 grav_y                             0.000000000               0.000000000    
 grav_z                             0.000000000               0.000000000    
 pressure                           1822.097819              0.1103080298E-02
 kineng                             5.972929171              0.8039804250E-01
 soundspeed                         104.4926291              0.2559481998E-02
 Gamma_1                           0.9947519887E-02          0.5970900293E-02
 MachNumber                        0.9991741484E-03          0.8285285189E-01
 entropy                            112050.1013              0.2923958757E-03
 magvort                            396.9629914              0.8486505161E-02
 divu                               2879.380154              0.9516350534    
 eint_E                             26389195.89              0.1419645656E-01
 eint_e                             26389195.89              0.1419645656E-01
 logden                            0.4663535575E-03          0.1219187735E-03
 StateErr_0                        0.1115628510E-05          0.6756895483E-03
 StateErr_1                        0.5311598319E-02          0.4414354713E-03
 StateErr_2                        0.3587273765E-01          0.3587273765E-01
 X(A)                              0.3587273765E-01          0.3587273765E-01
 X(B)                              0.3575742022E-01          0.3575742022E-01
 X(C)                              0.3587273765E-01          0.3587273765E-01
 abar                              0.4440892099E-15          0.4440892099E-15
 x_velocity                         2.096306618              0.1010389318E-01
 y_velocity                         22.47688405              0.5817703068E-01
 z_velocity                         0.000000000               0.000000000    
 magvel                             22.47688659              0.5817699652E-01
 radvel                             22.47663843              0.8561743936E-01
 circvel                            16.08588177              0.5486079980E-01
 magmom                            0.3711371059E-01          0.9632303331E-01
 angular_momentum_x                 0.000000000               0.000000000    
 angular_momentum_y                 0.000000000               0.000000000    
 angular_momentum_z                0.3669361465E-01          0.2825243459    
 maggrav                            0.000000000               0.000000000  ```

**Comment by zingale** [comment]
given the change in BCs, I think this sort of difference is okay.

**Comment by maxpkatz** [comment]
What's different between this problem's BC and the centralized HSE BC?

**Review by maxpkatz — APPROVED** [review]

**Comment by zingale** [comment]
The old BC integrated the initial model analytic profile into the ghost cells. For an isentropic atmosphere, this used the proper isentropic profile. Now we interpolate T into the ghost cells and integrate p via HSE. So it is not exactly the same as the analytic profile. I think it is good enough for a general HSE BC.

In the future, we could have the general HSE BC allow for an isentropic profile in the ghost cells too. That actually would not be too hard to add.

**Pull request merged**
