### PR TITLE
convert evrard_collapse to C++

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Review by maxpkatz — APPROVED** [review]

**Comment by zingale** [comment]
the errors are not small: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-12-13/evrard_collapse.html

**Comment by zingale** [comment]
I wonder if the issue here is that we are not setting small_pres and small_ener in C++, whereas before that info was never propagated to C++.

**Comment by zingale** [comment]
actually the issue is that this problem is just really sensitive.  Just tweaked some floating point operations.

**Comment by zingale** [comment]
errors are much smaller now: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-12-13-005/evrard_collapse.html

**Pull request merged**
