### PR TITLE
include pressure in x-momentum flux in 1-d Cartesian

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

previously, we were explicitly adding the pressure gradient in the conservative update
to the momentum for all 1-d geometries.  But we were only doing the flux correction
on P_radial for non-Cartesian geometries.  Now we treat all Cartesian geometries the
same, regardless of dimensionality.

This will likely change 1-d Cartesian answers.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-05-26-001/index.html

I need to understand what's happening with the SDC.  I am probably double-counting there.

**Comment by zingale** [comment]
updated tests:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-05-28-001/index.html

**Comment by zingale** [comment]
it looks like the 1-d true SDC tests are now roundoff, although I am not sure why we'd even get that change.

**Comment by maxpkatz** [comment]
Do you know what is up with rad2Tshock-1D in that test suite run?

**Comment by zingale** [comment]
the grids are different, so fcompare aborted.

**Review by maxpkatz — APPROVED** [review]

**Comment by zingale** [comment]
Here's the true-SDC (2nd order) Sod problem

sod_1d

**Comment by zingale** [comment]
Here's the PPM Sod problem with 2 levels of refinement, again using this PR

sod_1d

**Comment by zingale** [comment]
Here's a 2D sph_in_cylcoords Sedov with 4 levels

sedov_2d_sph_in_cyl

**Comment by zingale** [comment]
closes #2467

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-10-05-002/index.html

most are reasonable, but with Detonation, all bets are off (as always).

**Pull request merged**
