### PR TITLE
Convert ca_gsrc to C++

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
test results: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-06-21-003/index.html
some failures

**Comment by maxpkatz** [comment]
The failures are consistent with roundoff error.

**Comment by zingale** [comment]
why do you expect roundoff diffs?

**Comment by maxpkatz** [comment]
I don't necessarily expect it but there are a number of changes like using `+=` and replacing `sum(arr(:)**2)` with `(arr[0] * arr[0] + ...)` that could explain it.

**Pull request merged**
