### PR TITLE
Convert center to auto prob params

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-22-001/index.html

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-23-001/index.html

**Comment by maxpkatz** [comment]
The only failure was RadSuOlson which was due to a flaw in my logic in the probdata script (for the case with a non-zero number of parameters but none of which use the fortin namelist). This has been fixed so we can retest.

**Comment by zingale** [comment]
retest: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-23-002/index.html

**Comment by maxpkatz** [comment]
That crashes because the problem doesn't call `probdata_init()`. This is a problem because we cannot assume external setups will know to call it, so fixing it in all of the problems in Exec/ is not a real solution. I'll need to remove the dependence on the problem calling it in a separate PR before we can merge this one.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-23-006/index.html
now Sedov fails to compile

**Comment by maxpkatz** [comment]
Sedov should be fixed

**Review by zingale — APPROVED** [review]

**Pull request merged**
