### PR TITLE
Add chemical potential to State_Type

### PR DESCRIPTION
**Pull request by zhichen3**
## PR summary
Add chemical potential to State_Type instead of creating a separate StateData.
Addresses Issue #2347 

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
I think we also need to zero out the flux for these new components too, since hydro shouldn't change them.  Look in `Castro_ctu_hydro.cpp`, `Castro_mol_hydro.cpp`, `advection_util.cpp`, `riemann.H`, `riemann_solvers.H`, and `riemann_util.cpp` to see how `UTEMP` is handled.

There might be more places

**Comment by zhichen3** [comment]
> I think we also need to zero out the flux for these new components too, since hydro shouldn't change them. Look in `Castro_ctu_hydro.cpp`, `Castro_mol_hydro.cpp`, `advection_util.cpp`, `riemann.H`, `riemann_solvers.H`, and `riemann_util.cpp` to see how `UTEMP` is handled.
> 
> There might be more places

ah, okay.

**Comment by zhichen3** [comment]
With the microphysics pr#1122 merged (fixes the problems caused during the hybrid solver), I ran valgrind with `nse_test`  and still got some errors. The first few ones I got are:

`=94910== Conditional jump or move depends on uninitialised value(s)
==94910==    at 0x469816: operator() (Castro.cpp:3638)
==94910==    by 0x469816: call_f<Castro::reset_internal_energy(const amrex::Box&, amrex::Array4<double>)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:29)
==94910==    by 0x469816: ParallelFor<Castro::reset_internal_energy(const amrex::Box&, amrex::Array4<double>)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:168)
==94910==    by 0x469816: Castro::reset_internal_energy(amrex::Box const&, amrex::Array4<double>) (Castro.cpp:3590)
==94910==    by 0x471B8F: Castro::reset_internal_energy(amrex::MultiFab&, int) (Castro.cpp:3675)
==94910==    by 0x471F70: Castro::computeTemp(amrex::MultiFab&, double, int) (Castro.cpp:3877)
==94910==    by 0x492023: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:113)
==94910==    by 0x492DC4: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==94910==    by 0x491291: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==94910==    by 0x6C7345: timeStep (AMReX_Amr.cpp:2017)
==94910==    by 0x6C7345: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==94910==    by 0x43BF99: main (main.cpp:171)
==94910==  Uninitialised value was created by a stack allocation
==94910==    at 0x5247E3: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const [clone .constprop.0] (Castro_react.cpp:79)
==94910== 
==94910== Conditional jump or move depends on uninitialised value(s)
==94910==    at 0x472741: reset_e<eos_re_t> (eos.H:103)
==94910==    by 0x472741: reset_inputs<eos_input_t, eos_re_t> (eos.H:182)
==94910==    by 0x472741: eos<eos_input_t, eos_re_t> (eos.H:425)
==94910==    by 0x472741: operator() (Castro.cpp:3930)
==94910==    by 0x472741: call_f<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:29)
==94910==    by 0x472741: ParallelFor<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:168)
==94910==    by 0x472741: Castro::computeTemp(amrex::MultiFab&, double, int) (Castro.cpp:3910)
==94910==    by 0x492023: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:113)
==94910==    by 0x492DC4: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==94910==    by 0x491291: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==94910==    by 0x6C7345: timeStep (AMReX_Amr.cpp:2017)
==94910==    by 0x6C7345: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==94910==    by 0x43BF99: main (main.cpp:171)
==94910==  Uninitialised value was created by a stack allocation
==94910==    at 0x5247E3: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const [clone .constprop.0] (Castro_react.cpp:79)

==94910== Conditional jump or move depends on uninitialised value(s)
==94910==    at 0x481E34: apply_ions<eos_re_t> (actual_eos.H:515)
==94910==    by 0x481E34: void actual_eos<eos_input_t, eos_re_t>(eos_input_t, eos_re_t&) (actual_eos.H:1292)
==94910==    by 0x472775: eos<eos_input_t, eos_re_t> (eos.H:435)
==94910==    by 0x472775: operator() (Castro.cpp:3930)
==94910==    by 0x472775: call_f<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:29)
==94910==    by 0x472775: ParallelFor<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:168)
==94910==    by 0x472775: Castro::computeTemp(amrex::MultiFab&, double, int) (Castro.cpp:3910)
==94910==    by 0x492023: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:113)
==94910==    by 0x492DC4: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==94910==    by 0x491291: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==94910==    by 0x6C7345: timeStep (AMReX_Amr.cpp:2017)
==94910==    by 0x6C7345: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==94910==    by 0x43BF99: main (main.cpp:171)
==94910==  Uninitialised value was created by a stack allocation
==94910==    at 0x5247E3: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const [clone .constprop.0] (Castro_react.cpp:79)
==94910== 
==94910== Conditional jump or move depends on uninitialised value(s)
==94910==    at 0x4F1F22C: log10 (w_log10_compat.c:30)
==94910==    by 0x4804E8: void apply_electrons<eos_re_t>(eos_re_t&) (actual_eos.H:156)
==94910==    by 0x481E8A: void actual_eos<eos_input_t, eos_re_t>(eos_input_t, eos_re_t&) (actual_eos.H:1294)
==94910==    by 0x472775: eos<eos_input_t, eos_re_t> (eos.H:435)
==94910==    by 0x472775: operator() (Castro.cpp:3930)
==94910==    by 0x472775: call_f<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:29)
==94910==    by 0x472775: ParallelFor<Castro::computeTemp(amrex::MultiFab&, amrex::Real, int)::<lambda(int, int, int)> > (AMReX_GpuLaunchFunctsC.H:168)
==94910==    by 0x472775: Castro::computeTemp(amrex::MultiFab&, double, int) (Castro.cpp:3910)
==94910==    by 0x492023: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:113)
==94910==    by 0x492DC4: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==94910==    by 0x491291: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==94910==    by 0x6C7345: timeStep (AMReX_Amr.cpp:2017)
==94910==    by 0x6C7345: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==94910==    by 0x43BF99: main (main.cpp:171)
==94910==  Uninitialised value was created by a stack allocation
==94910==    at 0x5247E3: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const [clone .constprop.0] (Castro_react.cpp:79)`

**Comment by zhichen3** [comment]
If I run with `DEBUG=TRUE` then the first few are:

```
257136== Conditional jump or move depends on uninitialised value(s)
==257136==    at 0x69EDE6: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int) (Castro_react.cpp:274)
==257136==    by 0x47BA43: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:112)
==257136==    by 0x47CC2B: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==257136==    by 0x474738: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==257136==    by 0xA07569: amrex::Amr::timeStep(int, double, int, int, double) (AMReX_Amr.cpp:2017)
==257136==    by 0xA07D4F: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==257136==    by 0x4A9BE8: main (main.cpp:171)
==257136==  Uninitialised value was created by a stack allocation
==257136==    at 0x684435: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const (Castro_react.cpp:79)
==257136== 
==257136== Conditional jump or move depends on uninitialised value(s)
==257136==    at 0x69EDF1: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int) (Castro_react.cpp:274)
==257136==    by 0x47BA43: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:112)
==257136==    by 0x47CC2B: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==257136==    by 0x474738: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==257136==    by 0xA07569: amrex::Amr::timeStep(int, double, int, int, double) (AMReX_Amr.cpp:2017)
==257136==    by 0xA07D4F: amrex::Amr::coarseTimeStep(double) (AMReX_Amr.cpp:2124)
==257136==    by 0x4A9BE8: main (main.cpp:171)
==257136==  Uninitialised value was created by a stack allocation
==257136==    at 0x684435: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const (Castro_react.cpp:79)
==257136== 
==257136== Conditional jump or move depends on uninitialised value(s)
==257136==    at 0x50623D8: __printf_fp_l (printf_fp.c:396)
==257136==    by 0x506D61C: UnknownInlinedFun (vfprintf-internal.c:354)
==257136==    by 0x506D61C: __vfprintf_internal (vfprintf-internal.c:1061)
==257136==    by 0x508E35B: __vsnprintf_internal (vsnprintf.c:114)
==257136==    by 0x4DD3462: std::__convert_from_v(__locale_struct* const&, char*, int, char const*, ...) (c++locale.h:97)
==257136==    by 0x4E0493A: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_float<double>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, char, double) const (locale_facets.tcc:1023)
==257136==    by 0x4E14A9D: put (locale_facets.h:2463)
==257136==    by 0x4E14A9D: std::ostream& std::ostream::_M_insert<double>(double) (ostream.tcc:73)
==257136==    by 0x435915: amrex::Print& amrex::Print::operator<< <double>(double const&) (AMReX_Print.H:91)
==257136==    by 0x69EE4E: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int) (Castro_react.cpp:275)
==257136==    by 0x47BA43: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:112)
==257136==    by 0x47CC2B: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==257136==    by 0x474738: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==257136==    by 0xA07569: amrex::Amr::timeStep(int, double, int, int, double) (AMReX_Amr.cpp:2017)
==257136==  Uninitialised value was created by a stack allocation
==257136==    at 0x684435: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const (Castro_react.cpp:79)
==257136== 
==257136== Conditional jump or move depends on uninitialised value(s)
==257136==    at 0x50623F2: __printf_fp_l (printf_fp.c:396)
==257136==    by 0x506D61C: UnknownInlinedFun (vfprintf-internal.c:354)
==257136==    by 0x506D61C: __vfprintf_internal (vfprintf-internal.c:1061)
==257136==    by 0x508E35B: __vsnprintf_internal (vsnprintf.c:114)
==257136==    by 0x4DD3462: std::__convert_from_v(__locale_struct* const&, char*, int, char const*, ...) (c++locale.h:97)
==257136==    by 0x4E0493A: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_float<double>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, char, double) const (locale_facets.tcc:1023)
==257136==    by 0x4E14A9D: put (locale_facets.h:2463)
==257136==    by 0x4E14A9D: std::ostream& std::ostream::_M_insert<double>(double) (ostream.tcc:73)
==257136==    by 0x435915: amrex::Print& amrex::Print::operator<< <double>(double const&) (AMReX_Print.H:91)
==257136==    by 0x69EE4E: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int) (Castro_react.cpp:275)
==257136==    by 0x47BA43: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:112)
==257136==    by 0x47CC2B: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==257136==    by 0x474738: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==257136==    by 0xA07569: amrex::Amr::timeStep(int, double, int, int, double) (AMReX_Amr.cpp:2017)
==257136==  Uninitialised value was created by a stack allocation
==257136==    at 0x684435: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const (Castro_react.cpp:79)
==257136== 
==257136== Conditional jump or move depends on uninitialised value(s)
==257136==    at 0x505D416: __mpn_extract_double (dbl2mpn.c:56)
==257136==    by 0x5062BD6: __printf_fp_l (printf_fp.c:396)
==257136==    by 0x506D61C: UnknownInlinedFun (vfprintf-internal.c:354)
==257136==    by 0x506D61C: __vfprintf_internal (vfprintf-internal.c:1061)
==257136==    by 0x508E35B: __vsnprintf_internal (vsnprintf.c:114)
==257136==    by 0x4DD3462: std::__convert_from_v(__locale_struct* const&, char*, int, char const*, ...) (c++locale.h:97)
==257136==    by 0x4E0493A: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_float<double>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, char, double) const (locale_facets.tcc:1023)
==257136==    by 0x4E14A9D: put (locale_facets.h:2463)
==257136==    by 0x4E14A9D: std::ostream& std::ostream::_M_insert<double>(double) (ostream.tcc:73)
==257136==    by 0x435915: amrex::Print& amrex::Print::operator<< <double>(double const&) (AMReX_Print.H:91)
==257136==    by 0x69EE4E: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int) (Castro_react.cpp:275)
==257136==    by 0x47BA43: Castro::do_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:112)
==257136==    by 0x47CC2B: Castro::subcycle_advance_ctu(double, double, int, int) (Castro_advance_ctu.cpp:692)
==257136==    by 0x474738: Castro::advance(double, double, int, int) (Castro_advance.cpp:57)
==257136==  Uninitialised value was created by a stack allocation
==257136==    at 0x684435: Castro::react_state(amrex::MultiFab&, amrex::MultiFab&, double, double, int)::{lambda(int, int, int)#1}::operator()(int, int, int) const (Castro_react.cpp:79)
```

**Review by zingale — APPROVED** [review]

**Pull request merged**
