### PR TITLE
update the clang-tidy options

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by yut23** [comment]
It looks like `-header-filter=Castro` only checks header files with "Castro" in the name.

**Comment by zingale** [comment]
oh interesting.  Not sure why that was added.  Maybe we should remove it?

**Comment by yut23** [comment]
I've done some more digging and testing, and `-header-filter` does check part of the path as well. I'm pretty sure it matches against paths like `<include directory>/<file name>`, where `<include directory>` is one of the `-I` flags in compile_commands.json.

Based on that, something like `-header-filter='/Source/|/Util/model_parser_cxx|^\./'` should cover all of the non-generated Castro sources and the problem setups.

**Comment by zingale** [comment]
It doesn't like that change to the header:

```
/bin/sh: 1: ^./: not found
407
/bin/sh: 1: /Util/model_parser_cxx: not found
408
Unable to run clang-tidy.```

**Comment by yut23** [comment]
That's almost certainly a quoting issue. https://github.com/AMReX-Astro/cpp-linter-action/pull/2 should fix it.

**Comment by zingale** [comment]
okay this works now.

**Comment by zingale** [comment]
closing this in favor of #2381

**Pull request closed without merging**
