### PR TITLE
split out the MHD Initialization so we can run MHD on any problem

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

This gives us a separate Prob_mhd_nd.F90 that initiializes the magnetic field to 0.  Problems can implement their own version of this.  By providing this default we can run the MHD solver on any problem setup.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
test result: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-05-03-003/index.html

Sod fails because of the change in the number of timesteps from a previous PR

**Comment by zingale** [comment]
ah, thanks.  I'll update those problems and remove the prints

**Comment by zingale** [comment]
I think I've updated these -- not sure if we still want B as a probin parameter in some of the hydro problems.

**Comment by guadabsb15** [comment]
Yes, we don't really need those

**Pull request merged**
