### PR TITLE
merge some of the CTU code into a dimension-agnostic version

### PR DESCRIPTION
**Pull request by zingale**
This merges the main driver for the CTU hydro into a dimension agnostic driver.  Tests are still running, but everything seems to pass now.  The next step is probably to merge `consup`.  The rest probably will stay dimensional-specific, since the transverse updates vary a lot between dimensionality.

### CODE REVIEW

**Comment by zingale** [comment]
this is ready for review.  All tests passed.

**Comment by zingale** [comment]
review ping!

**Comment by maxpkatz** [comment]
The area arrays got added to the interface for umeth, but they aren't actually needed there, are they?

**Comment by zingale** [comment]
they are used in 1- and 2-d for the divu stuff

**Comment by zingale** [comment]
err... sorry, only 2-d for the transverse stuff

**Pull request merged**
