### PR TITLE
Move ctoprim to separate MFIter loop

### PR DESCRIPTION
**Pull request by maxpkatz**
The loop to do ctoprim is not slabbed like the PPM and Riemann solve are, so we get no real performance benefit from including it in the same MFIter loop. But we do take a performance hit because we are unnecessarily doing redundant work on ghost zones. This change removes the unnecessary ghost zone work, at the cost of allocating the whole array of primitive variables at one time.

### CODE REVIEW

**Comment by zingale** [comment]
are you sure that we don't need the ghost cell loop for radiation?

**Comment by maxpkatz** [comment]
What's different about radiation?

**Comment by zingale** [comment]
does this mean at a C-F interface, we are now interpolating all of the quantities instead of making them thermodynamically consistent via the EOS?

**Comment by maxpkatz** [comment]
It's not doing anything differently. It's just storing the work in a MultiFab rather than a series of temporary Fabs.

**Comment by zingale** [comment]
do we think that this is ready to be merged?

**Comment by maxpkatz** [comment]
I think it is correct but I am still uncertain whether we want to do this. So I'm going to leave it dormant for the moment.

**Comment by maxpkatz** [comment]
I am now in favor of doing this. This is ready for review.

**Comment by zingale** [comment]
this passed tests to roundoff

**Pull request merged**
