### PR TITLE
add option castro.allow_non_unit_aspect_zones

### PR DESCRIPTION
**Pull request by zingale**
this will allow the code to run with dx != dy without aborting.
Most of the solvers should work fine with non-unit aspect zones, but this
has not been rigorously tested

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
quick tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-08-03-001/index.html
the 2 crashes are due to an AMReX bug.

**Comment by zingale** [comment]
here's a Sedov test with zones 2x wider than tall:

test

**Comment by zingale** [comment]
according to Weiqun, AMReX is fine with dx != dy != dz, except for the Embedded Boundary stuff (which we don't use).

**Comment by zingale** [comment]
I can test this by running a simulation with wide aspect zones in x and then the same but in y, transposing the y and doing a diff and taking the norm.  Notebooks doing this using yt are included in this PR for acoustic_pulse and diffusion_test.

Here's the diffs from acoustic_pulse, when running with 128x32 zones and 32x128 zones on the unit domain.

```
Gamma_1              :                              0                              0
MachNumber           :       3.486848396822006535e-15      1.1169784170317064569e-08
StateErr_0           :      8.6597395920762210153e-15      6.1853431346847923539e-15
StateErr_1           :      3.4741585727227162345e-23      4.0394564416471441531e-15
StateErr_2           :                              0                              0
Temp                 :      3.4741585727227162345e-23      4.0394564416471441531e-15
X(X)                 :                              0                              0
abar                 :                              0                              0
angular_momentum_x   :                              0                            nan
angular_momentum_y   :                              0                            nan
angular_momentum_z   :      0.00050257700846702388527          2.0000000277233436208
circvel              :      1.6511183901724365989e-13       2.514468565854754948e-07
density              :      8.6597395920762210153e-15      6.1853431346847923539e-15
divu                 :      1.7768772564430435068e-13      7.5474003048998369348e-11
eint_E               :       7.771561172376095783e-15      4.3471776964615267299e-15
eint_e               :       7.771561172376095783e-15      4.3471776964615267299e-15
entropy              :          1.430511474609375e-06                             -0
kineng               :      2.9436088982981445383e-17      2.2339569261065091854e-08
logden               :      2.6922908347160046105e-15      1.8422552100513983869e-14
magmom               :      4.8826502736798449433e-15       1.116978399106998879e-08
magvel               :       3.486983922093567223e-15      1.1169784811136793481e-08
magvort              :      9.7991710232281370452e-14      1.0083127270957738563e-07
pressure             :      7.1054273576010018587e-15      7.1051604296348248386e-15
radvel               :      3.5338485609992531522e-15      1.3147127990402732538e-08
rho_E                :      1.8207657603852567263e-14      7.2827894398124130773e-15
rho_X                :      8.6597395920762210153e-15      6.1853431346847923539e-15
rho_e                :      1.8207657603852567263e-14      7.2827894403756928958e-15
soundspeed           :      1.9984014443252817728e-15      1.9972769177124269767e-15
x_velocity           :      1.9626625831817810786e-15       5.720369004279506847e-09
xmom                 :      2.7477791160576865714e-15       5.720368016341113422e-09
y_velocity           :      3.5666050191354714549e-15      2.2893242357378631967e-08
ymom                 :      4.9941062570113547991e-15      2.2893241612379650733e-08
z_velocity           :                              0                            nan
zmom                 :                              0                            nan```

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
