### PR TITLE
switch to the init provided by Microphysics

### LINKED ISSUE #1194: have castro use microphysics_init
Since we are using the interfaces from `Microphysics/interfaces/`, we should use the `microphysics_init()` routine there to initialize the EOS, network, and other stuff.  This way we don't need to maintain our own versions in `Castro_nd.F90`.  The one trick is that currently it takes optional arguments, so we'll need to provide a C-safe wrapper.

### PR DESCRIPTION
**Pull request by zingale**
closes #1194

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
requires https://github.com/starkiller-astro/Microphysics/pull/391

**Comment by maxpkatz** [comment]
In Fortran, the reason we pass small_temp and small_dens to EOS initialization is that small_temp and small_dens may be altered (if they're smaller than the EOS mintemp and mindens). In C++ that is done separately here: https://github.com/AMReX-Astro/Castro/blob/8b1da109c99412a6c1af9d7dd2d6b381a1c7939b/Source/driver/Castro_setup.cpp#L240-L249

I'm not sure which approach I like more, but if we're going to keep this bit of code, then we don't need to pass small_temp and small_dens to the EOS. But I don't think it's a good idea if we have the same code in both Castro and Microphysics, so perhaps if we want to keep the C++ version we should do the same thing in Fortran.

**Comment by zingale** [comment]
I'm not sure I fully understand.  Ultimately, I want small_dens and small_temp to be set in C++ and propagated elsewhere as needed.

I don't see why we don't need that extra code, but perhaps I should move it to before the initialization?

**Comment by maxpkatz** [comment]
What I'm saying is that the bit in those ten lines of code is also done in the Fortran eos_init. So now it's being done twice. One possible conclusion is that we just don't need to pass small_temp and small_dens to Fortran.

**Comment by zingale** [comment]
okay, this now calls microphysics_init from Fortran

**Comment by maxpkatz** [comment]
I am good with this now; let's see what the test suite says.

**Comment by zingale** [comment]
tests look good: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-06/index.html

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
