### PR TITLE
Guard attributes(managed) with AMREX_USE_GPU_PRAGMA

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
GPU tests: http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2020-11-04-001/index.html

**Comment by maxpkatz** [comment]
Those Sedov failures are because we have already turned off USE_GPU_PRAGMA and so we need to fix a couple of separate issues, porting tagging (#1293) and ambient data to C++. When that's done we can revisit this.

**Comment by maxpkatz** [comment]
Now that #1293 and #1295 have been merged this should be good to go now.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
gpu tests: http://groot.astro.sunysb.edu/Castro/test-suite/gpu/

**Comment by zingale** [comment]
CPU tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-05-004/index.html

**Pull request merged**
