### PR TITLE
fix the wdmerger case when the 2 stars are very close

### PR DESCRIPTION
**Pull request by zingale**
the initialization was overlapping and doing bad things now we simply look at which model provides the largest density at a location and use that.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
Here's the wdmerger 2D collision test case now:

image

compare to the image in #2824

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2024-04-20/index.html

**Review by yut23 — COMMENTED** [review]
The velocities need to be corrected too. I think the same condition should work.

**Comment by zingale** [comment]
velocities updated, but I want to rerun the suite on this now.

**Review by yut23 — APPROVED** [review]

**Pull request merged**
