### PR TITLE
use the new AUTO_BUILD_SOURCES amrex GNU Make feature

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
quick tests pass: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-06-11-004/index.html

**Comment by maxpkatz** [comment]
I recommend updating the submodules.

**Comment by zingale** [comment]
yes, good point

**Comment by zingale** [comment]
done

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
