### PR TITLE
don't allocate memory in prim state q for passives

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

We can create the primitive variable passives as needed in the tracing routines
from the conserved state, saying on memory (with ghost cells) in the primitive
variable array q

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
depends on #2181

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-05-05-004/index.html
fixed sdc tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-05-05-005/index.html

**Comment by zingale** [comment]
this does part of #1707

**Comment by zingale** [comment]
GPU tests: http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2022-05-05-002/index.html

**Comment by maxpkatz** [comment]
Can you do a version without rho_inv_arr and see how different it is in runtime (both on CPU and GPU)?

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
