### PR TITLE
Always use previous phi as guess for solve

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR summary

The Poisson solve has an option to not use the previous gravitational potential as a guess for the new solve (instead, a monopole solve is done and used to fill the domain). This is only used after initialization or restart. This option is now turned off, so that we always use the previous phi. At initialization we will pay a (one-time) larger cost to do the solve, but this should have no other effects.

## PR motivation

I would like to remove make_radial_phi; for the most part we don't need it and it makes monopole gravity harder to maintain. If this bit is removed then the only remaining use of make_radial_phi is in the BCs for the Poisson solve, and there it can be replaced entirely with the multipole BCs.

## PR checklist

- [x] test suite needs to be run on this PR
- [x] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-06-28-003/index.html

**Comment by maxpkatz** [comment]
> 
> 
> tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-06-28-003/index.html

Some of those failures are from the branch not being even with development, that's now resolved

**Comment by maxpkatz** [comment]
Updated tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-06-29-002/index.html

This is consistent with my expectation. The maximum diffs are consistent with the tolerance in the Poisson gravity solve, and the time taken is about the same. This is ready for review.

**Comment by zingale** [comment]
latest tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-06-29-002/index.html

**Comment by zingale** [comment]
The Poisson solve has an option to not use the previous gravitational potential as a guess for the new solve (instead, a monopole solve is done and used to fill the domain). This is only used after initialization or restart. This option is now turned off, so that we always use the previous phi. At initialization we will pay a (one-time) larger cost to do the solve, but this should have no other effects.

I would like to remove make_radial_phi; for the most part we don't need it and it makes monopole gravity harder to maintain. If this bit is removed then the only remaining use of make_radial_phi is in the BCs for the Poisson solve, and there it can be replaced entirely with the multipole BCs.

**Pull request merged**
