### PR TITLE
convert StarGrav to C++

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
B field stuff is not tested in the suite.  Here's the dipole field:

Screenshot from 2020-11-06 13-00-56
Screenshot from 2020-11-06 13-01-03
Screenshot from 2020-11-06 13-01-10

**Comment by zingale** [comment]
depends on #1298

**Comment by zingale** [comment]
errors seem big: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-06-006/StarGrav-2d.html

**Comment by zingale** [comment]
the difference seems to be most pronounced at a single zone right at the center.

curiously, the differences at step 0 are all O(1.e-12) or smaller

**Comment by maxpkatz** [comment]
We have tested this carefully and it is correct. The pronounced differences at timestep 25 turned out to be unrelated (#1373); the unrelated issue was unintentionally exposed due to small roundoff differences propagating a certain way in development and a different way in the new setup.

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
