### PR TITLE
Abort if mass fraction is unphysical

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-20-008/index.html
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-20-009/index.html

**Review by zingale — APPROVED** [review]

**Comment by maxpkatz** [comment]
Detonation-collision fails because it interpolates the burning on the fine level and that does not natively enforce 0 < X < 1.

**Comment by zingale** [comment]
I'll retest just the Detonations.

**Comment by zingale** [comment]
actually, I think we need `development` merged in first.

**Comment by maxpkatz** [comment]
Marking as draft until I figure out what to do about the reactions.max_solve_level interpolation issue.

**Comment by zingale** [comment]
do we still want to do this?

**Comment by maxpkatz** [comment]
Definitely. I just didn't want to break my science simulations. But since I'm not currently running those right now, maybe we should just merge this and solve that later.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-03-03-005/index.html

The SDC detonations fail -- I suspect that we are missing a normalization in that code.

**Comment by zingale** [comment]
in particular, these failures are all using VODE for the SDC solver, and we don't seem to have any normalization in the RHS there.  For the SDC Newton solve, we do have the normalization.

**Pull request merged**
