### PR TITLE
switch the computation of dtnuc_e to use the integral over the timestep

### PR DESCRIPTION
**Pull request by zingale**
for burns trying to reach equilibrium, this is better behaved

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
2 things:

1. do we want to make this an option?  So we can choose the integral or instantaneous?
2. I think I need to put Reactions_Type back into the checkpoint file for this

**Comment by zingale** [comment]
this seems to help a lot with `subchandra`

**Comment by zingale** [comment]
I no longer think that this is the way to go.

**Comment by zingale** [comment]
this is a plot of |de/dt| over 4 timesteps for the subchandra behind the inward propagating shock.  Given the large swings in the value here, this suggests that using the integral might be the better solution.

dedt

**Comment by maxpkatz** [comment]
If we're going to use information from during the previous burn then we more options than just the average. Particularly, we could record during the burn the maximum instantaneous energy generation rate after each burn step, and then take the max of that after the burn, and use that as the enuc value used in the timestep limiter.

**Pull request closed without merging**
