### PR TITLE
sdc do_hydro

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

This implemented the `castro.do_hydro` parameter for the SDC 2nd-order solver

## PR checklist

- [x] test suite needs to be run on this PR
- [x] this PR will change answers in the test suite
- [ ] all functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
blocked by #562 

also... still need to implement the 4th order version.

**Comment by zingale** [comment]
answers will change for SDC diffusion problems, since this fixes how the diffusion conductivities are computed.

**Comment by zingale** [comment]
this is ready for review

**Comment by maxpkatz** [comment]
Is it not possible to do this more cleanly by just not calling construct_mol_hydro_source if !do_hydro?

**Comment by zingale** [comment]
well... we still need to put the source term into the update.  But indeed, I suppose I could just copy the source over into the update in that case...

**Comment by zingale** [comment]
actually though, I want to experiment with doing diffusion via fluxes, so I still will want to get through this part of the code path.

**Comment by maxpkatz** [comment]
If we do diffusion via fluxes, it seems like there'd be no realistic way to do that without essentially doing the hydro update, since you still need to do the Riemann solve to have the data on edges. It would still be possible to disable do_hydro in that case, perhaps by calculating the hydro update but not applying it to the state. But that would still be done from the advance routine.

**Pull request merged**
