### PR TITLE
Sphinx conversion of docs

### PR DESCRIPTION
**Pull request by zingale**
This PR converts the docs to sphinx

### CODE REVIEW

**Comment by zingale** [comment]
Here's a current build of the docs:
http://bender.astro.sunysb.edu/random/Castro/docs/

**Comment by guadabsb15** [comment]
In the Microphysics section, \enskip seems to not be rendered correctly.
In the Checkpoint Embiggener , the figures are missing.

**Comment by zingale** [comment]
this closes #434

**Comment by zingale** [comment]
those should be fixed

**Comment by guadabsb15** [comment]
In the hydrodynamics section, under edge state prediction still showing some |\alpha_{i,\pm}|

**Comment by zingale** [comment]
I think I've addressed all of those

**Comment by zingale** [comment]
references are now implemented.

**Pull request merged**
