### PR TITLE
start working on a new interface for the approx state Riemann solvers

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
note that some problems like `rotating_torus` will have small diffs since immediately when we start, they have interface p or rhoe < 0, and we now reset this differently in the unified initialization approach.

In particular, we now use smallt and rho to get the interface state while previously we just did a max(p, small_pres).

**Comment by zingale** [comment]
GPU tests: http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2021-04-13-003/index.html

**Comment by zingale** [comment]
CPU tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-04-13-001/index.html

**Comment by zingale** [comment]
radiation tests pass: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-04-13-002/index.html

**Review by harpolea — APPROVED** [review]

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
