### PR TITLE
port the sponge to C++

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

This ports the sponge to C++, but it leaves the update_sponge_params routine in Fortran.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite
- [ ] all functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
test results: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-04-16-008/index.html

**Comment by zingale** [comment]
note that flame_wave is failing from a previous merge

**Comment by maxpkatz** [comment]
Looks good for CPU. You'll need to make sure lambda capture is working correctly for the CUDA build.

**Comment by zingale** [comment]
http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2020-04-17-003/index.html
GPU tests

**Pull request merged**
