### PR TITLE
we don't seem to use the outflow data in Fortran anymore

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by maxpkatz** [comment]
Do you remember what this data was for, because I don't.

**Comment by zingale** [comment]
my guess was that it was for setting monopole BCs for the gravity solve?

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-05-06-003/index.html

**Review by maxpkatz — APPROVED** [review]

**Review by maxpkatz — APPROVED** [review]

**Comment by maxpkatz** [comment]
For posterity, we think this is related to the old `spherical_star` functionality where you could represent a star which is bigger than the domain, and use the data from the domain corner to fill boundary conditions on the domain faces (which are geometrically closer to the center of the star).

**Pull request merged**
