### PR TITLE
Remove wdmerger tagging capability based on distance from center

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR summary

This capability is not currently used in any science setup so it is no longer needed.

## PR checklist

- [x] test suite needs to be run on this PR
- [x] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by maxpkatz** [comment]
The wdmerger_retry test was using this tagging scheme so that will need a reset. However the test still is subject to retries even without AMR so we should keep it in the suite.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
several tests crash: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-07-004/index.html

**Comment by maxpkatz** [comment]
Fixed

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-07-005/index.html

those failures are expected

**Pull request merged**
