### PR TITLE
Add support for early stopping based on exceeding some threshold value

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR summary

This was originally developed for wdmerger and Detonation, but now all applications should be able to use it.

`amr.message_int` is overridden to be 1 by default to support this.

## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [x] the `CHANGES` file has been updated, if appropriate
- [x] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2022-05-20-002/index.html

I think the diffs are because it doesn't have all of the changes on development

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
can you also update the docs here:
https://amrex-astro.github.io/Castro/docs/timestepping.html

**Comment by maxpkatz** [comment]
> can you also update the docs here: https://amrex-astro.github.io/Castro/docs/timestepping.html

I could, but this isn't really a timestepping constraint, so it seems a little out of place.

**Comment by zingale** [comment]
okay.  I just thought since at the top we list stopping criteria.  But we should find somewhere else to doc this.

**Pull request merged**
