### PR TITLE
F interface lohi

### PR DESCRIPTION
**Pull request by guadabsb15**
Here is for the issue  #296

### CODE REVIEW

**Comment by maxpkatz** [comment]
@zingale can you hit this with the test suite please

**Comment by zingale** [comment]
several problems fail because we still need to change the problem_tagging_?d routines in problem setup directories

**Comment by guadabsb15** [comment]
right! I totally forgot, I will modify those too

**Comment by zingale** [comment]
I'll rerun the failed tests

**Comment by zingale** [comment]
everything passes!

**Pull request merged**
