### PR TITLE
Switch from Fortran to C++ reactions

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR summary

The Fortran reactions interfaces (except for true SDC) are removed.

## PR checklist

- [x] test suite needs to be run on this PR
- [x] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [x] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by maxpkatz** [comment]
Initial test run: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-08-014/index.html

Most tests either pass or the diffs are acceptably small. But some tests (e.g. convective_flame) fail right out of the gate with burns that do not complete.

**Comment by maxpkatz** [comment]
The failing burns are due to the custom logic we have which prevents abundances from changing too much in a single integration step:

https://github.com/starkiller-astro/Microphysics/blob/ccd82d1e962b79e15d19fd77575b69e536550553/integration/VODE/vode_dvstep.H#L224-L228

The requirement for this logic is X > atol_spec, but atol_spec is 1.e-12 by default and that also happens to be our default small_x for many problems. So the trace species are trying to move away from small_x (to 1.e-10, say) and are not able to because those changes are much larger than the allowable VODE change factors.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
tests with the looser tolerances (https://github.com/starkiller-astro/Microphysics/pull/422)
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-11-10-005/index.html

The one crash is because the gridding is different now.

**Comment by zingale** [comment]
with the caveat that Detonation just is a bad test problem, I think the errors look fine.

**Comment by maxpkatz** [comment]
wdmerger_collision gets a lot slower, but we concluded that this is because the run is in debug mode -- there is no slowdown for optimized code. So this change looks good to me.

**Pull request merged**
