### PR TITLE
move all of the runtime parameter initialization to a central place

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-10-05-002/index.html

I'm not sure why the radiation stuff is failing

**Comment by zingale** [comment]
actually... I suspect it is because we do some magic after the radiation params are set and before the radsolve params are set
so perhaps I need to leave the radsolve params where they were for now.

**Comment by maxpkatz** [comment]
I'm OK with leaving RadSolve out for now. The parameters need to be dealt with more comprehensively there anyway.

**Comment by zingale** [comment]
updated to put the radsolve stuff back into the radsolve constructor so the radiation tests pass.  New tests:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-10-06-001/index.html

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
