### PR TITLE
remove derived in_nse plot var and rename new one to in_nse

### PR DESCRIPTION
**Pull request by zingale**
## PR motivation

We switched from deriving whether we are in NSE for the plotfiles and instead
using the NSE state stored in the Reactions_Type StateData.  This change eliminates
the duplicated derived `in_nse` plot variable and renames the new Reactions_Type
plot variable to `in_nse`.  This makes our scripts compatible with the way of computing
it without needing to change them.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zhichen3** [comment]
is this ready to review?

**Comment by zingale** [comment]
yes

**Comment by zhichen3** [comment]
should we also remove `ca_dernse` in `Derive.H` ?

**Comment by zingale** [comment]
yes, good catch.  I'll do that

**Comment by zingale** [comment]
done

**Pull request merged**
