### PR TITLE
add subch_base conditions with n14 frac

### PR DESCRIPTION
**Pull request by zhichen3**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zhichen3** [comment]
I updated the ci-benchmark but it still doesn't match...

**Comment by zingale** [comment]
I get a very different benchmark than you have in this PR.  Are you sure you are generating it correctly?  I did:

```
make DIM=1 USE_MPI=FALSE -j 2 USE_SIMPLIFIED_SDC=TRUE
./Castro1d.gnu.SMPLSDC.ex inputs-det-x.nse max_step=40 castro.time_integration_method=3
fextrema.gnu.ex det_x_plt00040 > ci-benchmarks/sdc_det_plt00040_extrema.out
```

**Comment by zhichen3** [comment]
pretty sure thats what I did. :/

**Comment by zingale** [comment]
Maybe your Microphysics is not up to date?

**Comment by zhichen3** [comment]
I think everything is up to date. Can you post the numbers you get? I ran it again on bender and got the same result

**Review by zingale — APPROVED** [review]

**Pull request merged**
