### PR TITLE
Mol cuda

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

This rewrites the CPU second-order (PLM/PPM) MOL hydro to be GPU friendly, and eliminates the need for a separate code path for the CUDA MOL.

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite
- [ ] all functions have docstrings as per the coding conventions

### CODE REVIEW

**Comment by zingale** [comment]
this addresses #490 and #477

**Comment by zingale** [comment]
the hydro part passes

the CUDA MOL path dies on Sedov with 
```
... hydro MOL stage 0
amrex::Abort::0::CUDA error in file tmp_build_dir/s/3d.pgi.CUDA.EXE/AMReX_CudaDevice.cpp line 294 an illegal memory access was encountered !!!
SIGABRT
```
the BackTrace points to:
```
    FArrayBox qe[AMREX_SPACEDIM];
```
in `Castro_mol_hydro.cpp`

**Comment by maxpkatz** [comment]
> the CUDA MOL path dies on Sedov 

Fixed in 1c0bb35. Unfortunately, the #pragma gpu is unforgiving -- all indices need to have AMREX_INT_ANYD, and all real variables need to be AMREX_REAL_ANYD (not ZFILL or AMREX_ZFILL). You got most of these, I think I got the rest. Also, scalars should be passed by value.

**Comment by zingale** [comment]
current status:

 * CPU MOL/SDC runs have hard 0 difference with `development`
 * GPU has rather large differences, O(1.e-3)

**Comment by maxpkatz** [comment]
This PR Is good by me. If you mark it ready for review, I'll merge.

**Pull request merged**
