### PR TITLE
we don't use the Fortran version of mom_flux_has_p anymore

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Review by harpolea — APPROVED** [review]

**Review by harpolea — CHANGES_REQUESTED** [review]
I think it also needs to be removed from `hydro/Castro_ctu_nd.F90`?

**Comment by zingale** [comment]
ooohh... we are still using it for radiation
let me convert that radiation consup to C++

**Comment by zingale** [comment]
I think this should be good now

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-09-22-007/index.html

**Review by maxpkatz — APPROVED** [review]

**Review by harpolea — APPROVED** [review]

**Pull request merged**
