### PR TITLE
implement SDC C++ reactions

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [x] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
Here's the output of the `reacting_convergence` test problem running the `convergence_simplified_sdc.sh` with C++ reactions and this PR:

```
 $\rho$                                   2.793739e+18   2.047               6.760321e+17   2.563                1.14437e+17
 $\rho u$                                 6.796293e+26   2.450                1.24349e+26   2.898                1.66881e+25
 $\rho v$                                 6.796293e+26   2.450                1.24349e+26   2.898                1.66881e+25
 $\rho E$                                 2.449871e+35   2.357               4.782716e+34   2.743                7.14447e+33
 $\rho e$                                 2.260884e+35   2.325               4.512537e+34   2.821               6.384886e+33
 $T$                                      2.235944e+21   1.690               6.929408e+20   2.473               1.247883e+20
 $\rho X(\isotm{He}{4})$                  2.877496e+18   2.023               7.078344e+17   2.536               1.220182e+17
 $\rho X(\isotm{C}{12})$                  1.697391e+17   1.947               4.401906e+16   2.222               9.436077e+15
 $\rho X(\isotm{O}{16})$                  1.687548e+14   1.658               5.349195e+13   1.950               1.384792e+13
 $\rho X(\isotm{Fe}{56})$                    279372900   2.047                   67603200   2.563                   11443700
```

**Comment by maxpkatz** [comment]
The Fortran version guards out the body of react_state_simplified_sdc if `SIMPLIFIED_SDC` is not defined because we don't compile in the correct version of the network bits in that case. I think we need to do the same thing here, or else the code would not compile for Strang.

**Comment by zingale** [comment]
for comparison, here's the Fortran convergence for the reacting_convergence test problem:

```
 $\rho$                                   2.794951e+18   2.044               6.776945e+17   2.554               1.154243e+17
 $\rho u$                                 6.798433e+26   2.449               1.245168e+26   2.889               1.680415e+25
 $\rho v$                                 6.798433e+26   2.449               1.245168e+26   2.889               1.680415e+25
 $\rho E$                                 2.452176e+35   2.352               4.803923e+34   2.742               7.179435e+33
 $\rho e$                                 2.262384e+35   2.321                4.52711e+34   2.822               6.404161e+33
 $T$                                      2.236308e+21   1.691                6.92676e+20   2.481               1.240441e+20
 $\rho X(\isotm{He}{4})$                  2.878726e+18   2.020               7.095514e+17   2.529               1.229444e+17
 $\rho X(\isotm{C}{12})$                  1.697096e+17   1.950               4.392694e+16   2.231               9.356683e+15
 $\rho X(\isotm{O}{16})$                  1.686238e+14   1.659               5.338323e+13   1.957               1.375377e+13
 $\rho X(\isotm{Fe}{56})$                    279494200   2.044                   67769440   2.554                   11542430
```

**Comment by zingale** [comment]
Here's the comparison between the C++ and Fortran 128^2 reacting_convergence with simplified_SDC:
```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                14.90307538           2.321416427e-05
 xmom                                    2510971794           4.966996209e-05
 ymom                                    2510959117           4.966971131e-05
 zmom                                             0                         0
 rho_E                              1.194465119e+18           3.218248343e-05
 rho_e                              1.185422492e+18           3.373765214e-05
 Temp                                    22871.2257           3.589099697e-05
 rho_He4                                15.81727949           2.470500463e-05
 rho_C12                                 1.54781629           4.510317917e-05
 rho_O16                             0.003685934612           0.0001022479747
 rho_Fe56                           1.490307538e-09           2.321416426e-05
 rho_omegadot_He4                       1240.479072           0.0001527919661
 rho_omegadot_C12                       191.5386814           0.0005124314115
 rho_omegadot_O16                      0.5425113958            0.002026269957
 rho_omegadot_Fe56                  1.278961999e-07           0.0001598850731
 rho_enuc                           1.467682786e+20           0.0002097219082
 burn_weights                                    17              0.5666666667
 pressure                           6.682945827e+17           3.077563887e-05
 kineng                             1.773064443e+17           8.615917313e-05
 soundspeed                             3793.929735           1.435640791e-05
 Gamma_1                            3.457077057e-06           2.176487349e-06
 MachNumber                         1.203225181e-05           3.451549217e-05
 entropy                                3390.987002           8.120693005e-06
 magvort                            0.0001232975793           0.0009645499263
 divu                                0.001350170388           8.122818217e-05
 eint_E                             2.645289324e+12           3.506755471e-05
 eint_e                             2.645289324e+12           3.506755471e-05
 logden                             1.264690519e-05           2.177676356e-06
 StateErr_0                             14.90307538           2.321416427e-05
 StateErr_1                              22871.2257           3.589099697e-05
 StateErr_2                         3.571957869e-06           3.573069218e-06
 X(He4)                             3.571957869e-06           3.573069218e-06
 X(C12)                             3.576524117e-06           4.241552348e-05
 X(O16)                             8.812826237e-09           9.949430589e-05
 X(Fe56)                              7.3992986e-21           7.399298454e-11
 abar                               1.069347133e-05           2.522909335e-06
 x_velocity                             3296.228694           4.048097513e-05
 y_velocity                             3296.237063           4.048107791e-05
 z_velocity                                       0                         0
 t_sound_t_enuc                     1.472698132e-05           0.0002184006125
 enuc                               2.757047639e+14           0.0001603362796
 magvel                                 3373.716675             4.1356189e-05
 radvel                                 3373.721385           4.135639155e-05
 circvel                                222.5640032            0.000612954091
 magmom                                  2516668937           4.961667615e-05
 angular_momentum_x                               0                         0
 angular_momentum_y                               0                         0
 angular_momentum_z                 1.580348424e+15           0.0005497713864
```

**Comment by zingale** [comment]
I've added the guard

**Comment by zingale** [comment]
tests pass: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-10-30-003/index.html

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
