### PR TITLE
Clean Sborder after FillPatch

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR summary

The FillPatch that creates Sborder from S_old can cause thermodynamically inconsistent states and/or small densities in the ghost zones, so we do need to clean Sborder (although as a later enhancement, we could change this clean to only operate on the ghost zones).

## PR checklist

- [x] test suite needs to be run on this PR
- [x] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-05-31-003/index.html

**Comment by maxpkatz** [comment]
A problem here is that clean_state requires the magnetic fields for MHD, but Sborder operates on NUM_GROW ghost zones which is than the magnetic fields have. So the call to reset_internal_energy won't make sense, because B doesn't have enough ghost zones.

**Comment by maxpkatz** [comment]
I don't see how to fix the MHD problem so for now I'm just ifdef'ing the call out when MHD is enabled. Please re-test.

**Comment by zingale** [comment]
can we use Bx_old, By_old, and Bz_old?

**Comment by maxpkatz** [comment]
No, they don't have enough ghost zones to do a clean_state over NUM_GROW ghost zones.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-06-02-001/index.html

**Comment by zingale** [comment]
`Detonation-collision-retry-SDC` failed with:


```amrex::Error::3::Invalid mass fraction in Castro::normalize_species() !!!```

**Comment by zingale** [comment]
I think that failure is just because the detonation is tricky and that check is actually meaningless at that point in the SDC algorithm.  I've seen this before with other SDC problems but haven't yet had time to address it.

**Comment by maxpkatz** [comment]
OK, I agree that this is not directly related to this change (it's crashing in a different call to clean_state than the one I added) so we can address it separately.

**Review by zingale — APPROVED** [review]

**Review by zingale — APPROVED** [review]

**Pull request merged**
