### PR TITLE
add a helper function that returns the fine grid dx

### PR DESCRIPTION
**Pull request by zingale**
this is for the case when we need dx before the level hierarchy is setup, like in problem_initialize.H

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
closes #669

**Comment by maxpkatz** [comment]
I think I am confused about whether we still need this. At this point, problem_initialize() is called in Castro::initMFs(), which is done in the Castro constructor after the Amr object has been created, so the geometry object on all levels should already be populated.

**Comment by zingale** [comment]
Oh.  Then how do I get the fine level dx?

**Comment by WeiqunZhang** [comment]
If you make `problem_initialize` a member function of Castro, you can get the Geometry on the max_level with `this->parent->Geom(this->parent->maxLevel())`. You can also change the interface of the function and pass `this` to `problem_initialize(Castro const*)`, if you don't want to make it a member function. It's basically the same thing. A member function has `this` as a hidden argument.

**Comment by WeiqunZhang** [comment]
Another possibility is to store a pointer to Amr after it's created in main.cpp as a global variable. Then you can access it from anywhere.

**Comment by zingale** [comment]
closing in facor of #2608

**Pull request closed without merging**
