### PR TITLE
change how we set variables to index state arrays

### PR DESCRIPTION
**Pull request by zingale**
We now list variable indices in a plain text file `_variables`.  These are used as the index keys into state
arrays both in C++ (for conserved state) and Fortran (for all the states).  This is the first part of a clean-up of how we define variables.  This addresses part of #267.  At the moment, we run the script `set_variables.py` manually to write the Fortran routines that C++ include file.  We also do some checking to ensure that we are synced up between C++ and Fortran.

### CODE REVIEW

**Comment by zingale** [comment]
This also eliminates `QRADVAR` -- we didn't need it, and simplifies the script that writes the method parameter stuff to group together parameters by if-def.

**Comment by zingale** [comment]
all tests pass now.  This is ready for review

**Comment by maxpkatz** [comment]
What is the difference between QVAR and NQ? It looks like NQ holds three extra variables, QPTOT, QREITOT, QRAD. What is special about them?

**Comment by zingale** [comment]
At the moment, QVAR is used for sources, NQ is used for primitive state arrays.  Those radiation variables don't have source terms.

We could change this such that we always use QVAR for state arrays and define an NQSRC for the primitive source array.

**Pull request merged**
