### PR TITLE
remove some deprecated AMReX constants / macros

### PR DESCRIPTION
**Pull request by zingale**
## PR motivation

This prepares us for https://github.com/AMReX-Codes/amrex/pull/3713

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I was also preparing for this yesterday. I just rebased my branch on yours. You might be able to cherry-pick the HEAD. https://github.com/WeiqunZhang/Castro/tree/amrex_prefix

**Comment by WeiqunZhang** [comment]
Note that I have not tested the patch in any ways.

**Comment by zingale** [comment]
I've merged your changes.  I didn't do Diagnostics or the radiation stuff yet, so that's in now.
I didn't do the Detonation  yet, because of #2722 but I'll fix that once that fix is in.

**Comment by zingale** [comment]
all the regression tests are passing now.

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
