### PR TITLE
on GPUs we were disabling the ext denfill BCs for the x-dir

### PR DESCRIPTION
**Pull request by zingale**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2020-09-30-001/index.html

**Comment by maxpkatz** [comment]
Do we know why this was disabled originally?

**Comment by zingale** [comment]
I suspect it was just a mistake

**Comment by maxpkatz** [comment]
OK, I agree it was an oversight. Commit 54cbab886834682513ee53c0f541211fcc39a63c added ext_denfill but not in the x direction, with an error case if calling in that mode that was ifdef'ed out for CUDA, presumably because we didn't have amrex_error for CUDA. Commit 18c497f39714806722c6c213e757b60b3643959f turned on CUDA support but x-direction support still wasn't there at that time; it was later added in #654, and the errors were replaced with the BC fill code but we forgot to remove the ifdef guarding out those errors.

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
