### PR TITLE
remove ghost cells from B and extra from state

### PR DESCRIPTION
**Pull request by guadabsb15**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2020-05-07-009/index.html

**Comment by zingale** [comment]
Not directly related to this PR, but I think we are not doing the new thermo source correct.

In `construct_new_thermo_source`, we call `fill_thermo_source` twice, first with the old state and we add -0.5 of that to `thermo_src` and then we call it a second time, and add 0.5 of that to `thermo_src`.  So the idea is that the new source should be of the form 

1/2 (S_new - S_old).

But in the second call, we are doing the time-centering ourselves, by averaging `state_old` and `state_new`.  I think we should only use `state_new`.  We can make this clearer by having `fill_thermo_source()` take only a single state.

**Comment by guadabsb15** [comment]
Thank you for pointing that out. I think it is fixed. I would appreciate if we do the change in fill_thermo_source in another PR, but I'm open to what you prefer. Taking care of the ghost cells, helps with further debugging.

**Comment by zingale** [comment]
okay, I'll open a different PR with that fix

**Pull request merged**
