### PR TITLE
switch true-SDC to completely use burn_t internally in the Newton solve

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

this eliminates some excess memory and copies

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
this currently doesn't work for some reason

**Comment by zingale** [comment]
it seems like this works now that we've merged #2606

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2023-10-09-006/index.html

**Comment by zingale** [comment]
this closes #2564 and #2563

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
