### PR TITLE
[WIP] Allocate arrays for sources in advected/species/auxilary equations

### PR DESCRIPTION
**Pull request by RemiLehe**
## PR motivation

When trying to add [source terms](https://amrex-astro.github.io/Castro/docs/Hydrodynamics.html#source-terms) in the species equations (e.g. using ` problem_source.H` file that modifies `src(i,j,k,UFS)`), I got an out-of-bound access error. With the changes in this PR, the error disappears.

## PR checklist

- [X] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by zingale** [comment]
we removed sources to the species to save memory, since we don't need them (for our SDC approach, we manually add the needed bits outside of the source).

If we want to add this back, we should do it as an option, since it can be a lot of memory when we have 20-30 species.

**Comment by RemiLehe** [comment]
Thanks for the feedback. 

How would the user turn the option on? Would that be controlled through the user's `GNUmakefile` for instance? (And how should I modify the PR accordingly.)

**Comment by zingale** [comment]
let me close this and do a new PR that has the option

**Comment by zingale** [comment]
closing in favor of #2678

**Pull request closed without merging**
