### PR TITLE
Convert DustCollapse setup to C++

### PR DESCRIPTION
**Pull request by maxpkatz**
## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

**Comment by maxpkatz** [comment]
Note: this problem setup had a bug in Fortran where the `xl` and `zl` indices reversed the correct indices in `problo`, but this didn't cause any issues because problo was always zero for this problem.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-05-16-005/index.html

**Comment by maxpkatz** [comment]
Fixed an issue with checking problo[2] in 2D

**Comment by zingale** [comment]
2-d passes now: http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2021-05-16-008/dustcollapse-2d-poissonn.html

**Review by zingale — APPROVED** [review]

**Pull request merged**
